import {useEffect, useState} from "react";
import {useNavigate, useParams} from "react-router-dom";
import axiosClient from "../axios-client.js";
import {useStateContext} from "../contexts/ContextProvider.jsx";

export default function ReservationDetails() {
    const {id} = useParams(); const navigate = useNavigate(); const {user} = useStateContext();
    const [reservation, setReservation] = useState(null); const [equipment, setEquipment] = useState([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
    useEffect(() => { Promise.all([axiosClient.get(`/reservations/${id}`), axiosClient.get("/equipment-items")]).then(([r, e]) => { setReservation({...r.data, equipment_item_ids: r.data.reserved_equipments.map((item) => item.id)}); setEquipment(e.data); }).catch(() => setError("Rezervaciju nije moguće učitati.")); }, [id]);
    const field = (key, value) => setReservation((current) => ({...current, [key]: value}));
    const selected = reservation?.equipment_item_ids || [];
    const editable = user?.role === "admin" && reservation && !["Zavrsena", "Otkazana"].includes(reservation.reservation_state?.name);
    const selectedItems = equipment.filter((item) => selected.includes(item.id));
    const save = async (event) => { event.preventDefault(); if (!selected.length) return setError("Rezervacija mora sadržavati najmanje jednu stavku opreme."); setSaving(true); setError(""); try { const {data} = await axiosClient.put(`/reservations/${id}`, {reservation_date: reservation.reservation_date?.slice(0, 10), return_date: reservation.return_date?.slice(0, 10), name: reservation.name, surname: reservation.surname, phone: reservation.phone, identification_document: reservation.identification_document || null, notes: reservation.notes || null, equipment_item_ids: selected}); setReservation({...data, equipment_item_ids: data.reserved_equipments.map((item) => item.id)}); } catch (requestError) { setError(requestError.response?.data?.message || "Promjene nije moguće sačuvati."); } finally { setSaving(false); } };
    if (!reservation) return <div className="detail-empty"><p>{error || "Učitavanje rezervacije..."}</p><button className="btn btn-outline-secondary" onClick={() => navigate("/reservations")}>Nazad na rezervacije</button></div>;
    return <div className="reservation-edit-page"><button className="detail-back" onClick={() => navigate("/reservations")}>← Nazad na rezervacije</button><div className="form-card reservation-edit-card"><h1 className="form-card-title">Rezervacija #{reservation.id}</h1><p className="form-card-subtitle">Uredite podatke kupca, datume i odabranu opremu.</p>{!editable && <div className="alert alert-info">Ovu rezervaciju možete pregledati, ali se njen status više ne može mijenjati.</div>}{error && <div className="alert alert-danger">{error}</div>}<form onSubmit={save}><fieldset disabled={!editable || saving}><div className="form-card-grid"><Input label="Ime" value={reservation.name} onChange={(value) => field("name", value)} /><Input label="Prezime" value={reservation.surname} onChange={(value) => field("surname", value)} /><Input label="Telefon" value={reservation.phone} onChange={(value) => field("phone", value)} /><Input label="Identifikacioni dokument" value={reservation.identification_document} onChange={(value) => field("identification_document", value)} optional /><Input label="Datum preuzimanja" type="date" value={reservation.reservation_date?.slice(0, 10)} onChange={(value) => field("reservation_date", value)} /><Input label="Datum vraćanja" type="date" value={reservation.return_date?.slice(0, 10)} onChange={(value) => field("return_date", value)} /><Input label="Napomena" value={reservation.notes} onChange={(value) => field("notes", value)} full textarea optional /><div className="form-card-field full"><label>Oprema u rezervaciji</label><div className="reservation-edit-items">{selectedItems.map((item) => <div key={item.id} className="reservation-edit-item"><span><strong>{item.name}</strong><small>{item.equipment_type?.name} · Veličina: {item.size || "—"} · Interni broj: {item.internal_registration_number || "—"}</small><small>{Number(item.price).toFixed(2)} KM/dan</small></span><button type="button" className="btn btn-outline-danger btn-sm" onClick={() => field("equipment_item_ids", selected.filter((itemId) => itemId !== item.id))}>Ukloni</button></div>)}</div></div></div></fieldset>{editable && <div className="form-card-actions mt-3 gap-2"><button type="button" className="btn btn-outline-secondary" onClick={() => navigate(`/sports?reservation=${reservation.id}`)}>Dodaj opremu</button><button className="btn btn-primary" disabled={saving}>{saving ? "Čuvanje..." : "Sačuvaj promjene"}</button></div>}</form></div></div>;
}
function Input({label, value, onChange, type = "text", full = false, textarea = false, optional = false}) { return <div className={`form-card-field ${full ? "full" : ""}`}><label>{label}</label>{textarea ? <textarea className="form-control" value={value || ""} onChange={(event) => onChange(event.target.value)} /> : <input required={!optional} className="form-control" type={type} value={value || ""} onChange={(event) => onChange(event.target.value)} />}</div>; }
